"""Core constants and action mapping for RLRL Gym."""

ACTION_MOVE_NORTH = 0
ACTION_MOVE_SOUTH = 1
ACTION_MOVE_WEST = 2
ACTION_MOVE_EAST = 3
ACTION_WAIT = 4
ACTION_LOOT = 5
ACTION_EAT = 6
ACTION_PICKUP = 7
ACTION_EQUIP = 8
ACTION_USE = 9
ACTION_INTERACT = 10
ACTION_ATTACK = 11
ACTION_GIVE = 12
ACTION_TRADE = 13
ACTION_REVIVE = 14
ACTION_GUARD = 15
ACTION_LEAVE_FACTION = 16
ACTION_ACCEPT_INVITE = 17
ACTION_DEFEND = 18
ACTION_INTERACT_RESOURCE = 19
ACTION_INTERACT_STATION = 20
ACTION_INTERACT_SHEAR = 21
ACTION_INTERACT_HARVEST = 22
ACTION_INTERACT_MINE = 23
ACTION_INTERACT_FORAGE = 24
ACTION_INTERACT_PLANT = 25
ACTION_INTERACT_FACTION = 26
ACTION_INTERACT_CHEST = 27
ACTION_INTERACT_SHRINE = 28
ACTION_INTERACT_DRINK = 29

ACTION_NAMES = {
    ACTION_MOVE_NORTH: "move_north",
    ACTION_MOVE_SOUTH: "move_south",
    ACTION_MOVE_WEST: "move_west",
    ACTION_MOVE_EAST: "move_east",
    ACTION_WAIT: "wait",
    ACTION_LOOT: "loot",
    ACTION_EAT: "eat",
    ACTION_PICKUP: "pickup",
    ACTION_EQUIP: "equip",
    ACTION_USE: "use",
    ACTION_INTERACT: "interact",
    ACTION_ATTACK: "attack",
    ACTION_GIVE: "give",
    ACTION_TRADE: "trade",
    ACTION_REVIVE: "revive",
    ACTION_GUARD: "guard",
    ACTION_LEAVE_FACTION: "leave_faction",
    ACTION_ACCEPT_INVITE: "accept_invite",
    ACTION_DEFEND: "defend",
    ACTION_INTERACT_RESOURCE: "interact_resource",
    ACTION_INTERACT_STATION: "interact_station",
    ACTION_INTERACT_SHEAR: "interact_shear",
    ACTION_INTERACT_HARVEST: "interact_harvest",
    ACTION_INTERACT_MINE: "interact_mine",
    ACTION_INTERACT_FORAGE: "interact_forage",
    ACTION_INTERACT_PLANT: "interact_plant",
    ACTION_INTERACT_FACTION: "interact_faction",
    ACTION_INTERACT_CHEST: "interact_chest",
    ACTION_INTERACT_SHRINE: "interact_shrine",
    ACTION_INTERACT_DRINK: "interact_drink",
}

ACTION_MAX = max(ACTION_NAMES.keys())

MOVE_DELTAS = {
    ACTION_MOVE_NORTH: (-1, 0),
    ACTION_MOVE_SOUTH: (1, 0),
    ACTION_MOVE_WEST: (0, -1),
    ACTION_MOVE_EAST: (0, 1),
}
